project:
  # This will be used as the vendor name in the new project's composer.json file.
  vendor_name: 'Reese Creative'
  # Everyone: This will determine the the directory name of the new repository.
  # Dev Desktop users: this should match your local site name.
  machine_name: 'reesecreativestudio'
  # Used for enforcing correct git commit msg syntax.
  prefix: 'RC'
  human_name: 'Reese Creative'
  profile:
    name: 'lightning'
    # Please ensure contrib profiles are also in your composer.json file.
    contrib: true
  # This is used to build front end artifacts. E.g., SASS compilation.
  themes:
    - thunder
  # These are random strings used to configure the hash salt.
  hash_salt: DQKwRRY6lr4HZHIseCKtzAsxYGA0xZOyex8a1RZetxZH2hnLcDnb7Xr
  # This will be used as the local uri for all developers.
  local:
    protocol: http
    hostname: reesecreativestudio.local

# Configuration settings for new git repository.
git:
  default_branch: develop
  remotes:
    # Defining git remotes allows builds deployed via CI.
    - git@github.com:darkcody/reesecreativestudio.git

drush:
  # You can set custom project aliases in drush/site-aliases/aliases.drushrc.php.
  aliases:
    # The remote environment from which the database will be pulled.
    remote: reesecreativestudio.test
    # The local environment against which all local drush commands are run.
    local: self
    # The drush alias against which all ci commands are run.
    ci: self
    # The default drush alias to be used when no environment is specified.
  default_alias: self

# Hosting environment flags.
# Examples: acsf (Acquia Cloud Site Factory), ac (Acquia Cloud)
# hosting: "acsf"
# hosting: "ac"
